language: node_js
node_js:
    - "9"
    - "8"
    - "7"
    - "6"
after_success:
	- ECHO ${GIT_PW}
  - npm version patch
  - git add -u
  - git commit -m "[ci skip] version changed"
  - git push origin develop